### ISSUE TITLE
Render GitHub emojis

### ISSUE THREAD

**Issue by sid-maddy** [hzsweers/CatchUp#64]
See trumail's description in the pic below.

![trumail](https://i.imgur.com/j2tKNa0.png)

**Comment by hzsweers** [comment]
Thanks for the report. I've seen this before but honestly have no idea how to handle it other than just having a giant (imperformant) string replacer with a mapping. Will need to think on it

**Comment by albinekb** [comment]
It's not very imperformant to replace the strings, there are libraries to do so (I only know in JS, so that won't help you there), but slack for example does this client side for every message, it won't add much overhead. As far as I know 👍

**Comment by hzsweers** [comment]
Good points! I did some research and I think there's some paths forward. From a high level, my thinking is:

* Create a regex for matching the aliases (basically `:thetext:`)
* Embed a DB for ROOM with this data - https://github.com/github/gemoji/blob/master/db/emoji.json. This keeps all this data from sitting in memory all the time unnecessarily.
* On alias regex matches in titles, query the DB for those aliases. Can do them in a blocking fashion since we're off the main thread. If I concatMapEager the graphql response -> `CatchUpItem` mapping, these can be done concurrently and quickly

**Comment by Tunous** [comment]
I previously added similar feature to OctoDroid GitHub app and found [emoji-java](https://github.com/vdurmont/emoji-java) library. It has a `EmojiParser.parseToUnicode` method for converting these aliases and it works very well. You might want to try using it.

**Comment by hzsweers** [comment]
Yeah I saw that. The particular appeal of a ROOM db to me was to just query as needed on matches rather than keep the entire mapping in memory. That library seems to read all of them up front from a json blob and keep them around

**Comment by albinekb** [comment]
I think that reading it to memory is the fastest way 2017? Most phones have 2GB+ RAM and the emoji mapping shouldn't be more than a couple KB? 🤔

**Comment by charlesdurham** [comment]
I've been messing around with this a bit [WIP](https://github.com/hzsweers/CatchUp/compare/master...charlesdurham:master).

Initially I thought I could use [emojis.json](https://github.com/github/gemoji/blob/master/db/emoji.json) as a general emoji markdown file, so that if there are ever other services that have emoji markdown, this would work for those as well. However, from what I can tell github doesn't support skin tones, so this file might not have been as general as I was hoping.

**Comment by hzsweers** [comment]
That branch looks really good, and I think your implementation is quite clever. I'm not teeeerribly worried about supporting this in other services for now, can always revisit and consider leveraging something more general like https://github.com/vdurmont/emoji-java does if need be.

![](https://media.giphy.com/media/11t9sYRP19MFd6/giphy.gif)

**Comment by hzsweers** [comment]
Sidenote - wonder how slack handles this. I know a few people on their team, will ask. My guess is it's all in-house as part of their markdown pipeline, but maybe they've got some pointers
